[package]
name = "wry"
version = "0.1.2"
authors = ["Ngo Iok Ui <wusyong9104@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "(WIP) A tiny webview library to build modern cross-platform GUIs."
readme = "README.md"

[dependencies]
libc = "0.2"
once_cell = "1.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
webkit2gtk = { version = "0.11.0", features = ["v2_8"] }
gio = "0.9"
gtk = "0.9"

[target.'cfg(target_os = "windows")'.dependencies]
windows = "0.2.1"
winit = "0.24"

[target.'cfg(target_os = "windows")'.build-dependencies]
cc = "1"
windows = "0.2.1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
core-graphics = "0.22"
objc = "0.2"
winit = "0.24"

