[package]
name = "yametekudastop"
version = "0.0.1"
authors = ["Ngo Iok Ui <wusyong9104@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "(WIP) A tiny webview library to build modern cross-platform GUIs."
readme = "README.md"

[dependencies]
libc = "0.2"
once_cell = "1.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
javascriptcore-rs-sys = "0.2"
gtk-sys = "0.10"
glib-sys = "0.10"
gobject-sys = "0.10"
webkit2gtk-sys = { version = "0.12", features = ["v2_8"] }
gdk-sys = "0.10"

[target.'cfg(target_os = "windows")'.dependencies]
winit = "0.24"
winapi = { version = "0.3", features = ["combaseapi", "libloaderapi", "minwindef", "roapi", "synchapi", "winbase", "windef", "winnt", "winuser"] }
#winrt = "0.7"
windows = "0.2.1"

[target.'cfg(target_os = "windows")'.build-dependencies]
cc = "1"
windows = "0.2.1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
core-graphics = "0.22"
objc = "0.2"

